name: Deploy static content to Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["main"]

  # Allows manual workflow runs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Run export_docs.py
      - name: Export API Docs
        run: |
          python export_docs.py

      # Step 4: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 5: Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'api-docs-my-project.html'

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
